// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: programmer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// [修饰符] 类型 字段名 = 标识符;
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_programmer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_programmer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_programmer_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 定义服务端响应的数据格式
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Job      string   `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	GoodAt   []string `protobuf:"bytes,4,rep,name=goodAt,proto3" json:"goodAt,omitempty"` // repeated 修饰符表示字段是可变数组，即 slice 类型
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_programmer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_programmer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_programmer_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Response) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Response) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *Response) GetGoodAt() []string {
	if x != nil {
		return x.GoodAt
	}
	return nil
}

var File_programmer_proto protoreflect.FileDescriptor

var file_programmer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6a, 0x6f, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x6f, 0x6f, 0x64, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x6f, 0x6f, 0x64, 0x41, 0x74, 0x32, 0x4b, 0x0a, 0x11,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_programmer_proto_rawDescOnce sync.Once
	file_programmer_proto_rawDescData = file_programmer_proto_rawDesc
)

func file_programmer_proto_rawDescGZIP() []byte {
	file_programmer_proto_rawDescOnce.Do(func() {
		file_programmer_proto_rawDescData = protoimpl.X.CompressGZIP(file_programmer_proto_rawDescData)
	})
	return file_programmer_proto_rawDescData
}

var file_programmer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_programmer_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: proto.Request
	(*Response)(nil), // 1: proto.Response
}
var file_programmer_proto_depIdxs = []int32{
	0, // 0: proto.ProgrammerService.GetProgrammerInfo:input_type -> proto.Request
	1, // 1: proto.ProgrammerService.GetProgrammerInfo:output_type -> proto.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_programmer_proto_init() }
func file_programmer_proto_init() {
	if File_programmer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_programmer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_programmer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_programmer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_programmer_proto_goTypes,
		DependencyIndexes: file_programmer_proto_depIdxs,
		MessageInfos:      file_programmer_proto_msgTypes,
	}.Build()
	File_programmer_proto = out.File
	file_programmer_proto_rawDesc = nil
	file_programmer_proto_goTypes = nil
	file_programmer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProgrammerServiceClient is the client API for ProgrammerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProgrammerServiceClient interface {
	// rpc 定义服务内的 GetProgrammerInfo 远程调用
	GetProgrammerInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type programmerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgrammerServiceClient(cc grpc.ClientConnInterface) ProgrammerServiceClient {
	return &programmerServiceClient{cc}
}

func (c *programmerServiceClient) GetProgrammerInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ProgrammerService/GetProgrammerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgrammerServiceServer is the server API for ProgrammerService service.
type ProgrammerServiceServer interface {
	// rpc 定义服务内的 GetProgrammerInfo 远程调用
	GetProgrammerInfo(context.Context, *Request) (*Response, error)
}

// UnimplementedProgrammerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProgrammerServiceServer struct {
}

func (*UnimplementedProgrammerServiceServer) GetProgrammerInfo(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgrammerInfo not implemented")
}

func RegisterProgrammerServiceServer(s *grpc.Server, srv ProgrammerServiceServer) {
	s.RegisterService(&_ProgrammerService_serviceDesc, srv)
}

func _ProgrammerService_GetProgrammerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammerServiceServer).GetProgrammerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProgrammerService/GetProgrammerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammerServiceServer).GetProgrammerInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProgrammerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProgrammerService",
	HandlerType: (*ProgrammerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProgrammerInfo",
			Handler:    _ProgrammerService_GetProgrammerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "programmer.proto",
}
